image: registry.gitlab.com/aleksandr-kotlyar/java-sitemap-checker
stages:
  - test

variables:
  SITEMAPURL: ''
  SOURCETYPE: ''
  DOMAIN: ''
  STREAMS: 10

.test:
  stage: test
  script:
    - mvn clean test -Dgroups=${SOURCETYPE} -DsitemapUrl=${SITEMAPURL} -Ddomain=${DOMAIN} -Dstreams=${STREAMS}
  only:
    - web

xml:
  extends: .test
  variables:
    SOURCETYPE: source.type.Xml

html:
  extends: .test
  variables:
    SOURCETYPE: source.type.Html